services:
  jupyter:
    build:
      context: images/jupyter
    env_file:
      - .env
    command:
      - "jupyter"
      - "lab"
      - "--ip"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--notebook-dir"
      - "/app/notebooks"
      - "--NotebookApp.token=''"
      - "--NotebookApp.password=''"
    user: ${UID:-1000}:${GUID:-20}
    volumes:
      - ./notebooks:/app/notebooks
    ports:
      - "8080:8080"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio1234
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    volumes:
      - minio:/data
  nessie:
    image: ghcr.io/projectnessie/nessie:0.100.0
    user: root
    ports:
      - "19120:19120"
    environment:
      - NESSIE_VERSION_STORE_TYPE=ROCKSDB
      - NESSIE_VERSION_STORE_PERSIST_ROCKS_DATABASE_PATH=/data/nessiestore
      - nessie.catalog.default-warehouse=warehouse
      - nessie.catalog.warehouses.warehouse.location=s3://warehouse/
      - nessie.catalog.service.s3.default-options.endpoint=http://minio:9000/
      - nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      - nessie.catalog.service.s3.default-options.path-style-access=true
      - nessie.catalog.secrets.access-key.name=minio
      - nessie.catalog.secrets.access-key.secret=minio1234
      - nessie.catalog.service.s3.default-options.region=us-east-1
      - nessie.server.authentication.enabled=false
    volumes:
      - nessie:/data/nessiestore
  dremio:
    image: dremio/dremio-oss:25.2
    platform: linux/x86_64
    ports:
      - "9047:9047"
      - "32010:32010"
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
      - DREMIO_JAVA_EXTRA_OPTS=-Ddebug.addDefaultUser=true
    volumes:
      - dremio:/opt/dremio

volumes:
  minio:
  nessie:
  dremio: