services:
  jupyter:
    build:
      context: images/jupyter
    environment:
      - FSSPEC_S3_ENDPOINT_URL=http://minio:9000
      - FSSPEC_S3_KEY=minio
      - FSSPEC_S3_SECRET=minio1234
    env_file:
      - .env
    command:
      - "jupyter"
      - "lab"
      - "--ip"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--notebook-dir"
      - "/app/notebooks"
      - "--NotebookApp.token=''"
      - "--NotebookApp.password=''"
    user: ${UID:-1000}:${GUID:-20}
    volumes:
      - ./notebooks:/app/notebooks
    ports:
      - 8080:8080
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio1234
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    volumes:
      - minio:/data
  nessie:
    image: ghcr.io/projectnessie/nessie:0.92.1
    user: root
    ports:
      - 19120:19120
    environment:
      - NESSIE_VERSION_STORE_TYPE=ROCKSDB
      - NESSIE_VERSION_STORE_PERSIST_ROCKS_DATABASE_PATH=/data/nessiestore
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_ACCESS_KEY_NAME=minio
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_ACCESS_KEY_SECRET=minio1234
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_ENDPOINT=http://minio:9000
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_REGION=us-east-1
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_PATH_STYLE_ACCESS=true
      - NESSIE_CATALOG_DEFAULT_WAREHOUSE=warehouse
      - NESSIE_CATALOG_WAREHOUSES_WAREHOUSE_LOCATION=s3://warehouse
    volumes:
      - nessie:/data/nessiestore
  dremio:
    image: dremio/dremio-oss:25.0
    platform: linux/x86_64
    ports:
      - 9047:9047
      - 32010:32010
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
      - DREMIO_JAVA_EXTRA_OPTS=-Ddebug.addDefaultUser=true
    volumes:
      - dremio:/opt/dremio

volumes:
  minio:
  nessie:
  dremio: